#!/bin/sh

APP=etl
DEPLOYDIR=~/python/app/$APP
CRONDIR=/etc/cron.d

GIT_WORK_TREE="$DEPLOYDIR" git checkout -f

cd "$DEPLOYDIR"

. ~/.virtualenvs/etl/bin/activate

pip install -r requirements.txt

sudo cp lib/crontab $CRONDIR/$APP"python"

echo 'All done :D'